In [23]:
import pandas as pd
p= pd.read_csv("products.csv")
s= pd.read_csv("suppliers.csv")

df= p.merge(s[["supplier_id","country"]], on ="supplier_id", how="left")

r= df[df["price"]==df.groupby("country")["price"].transform("max")].sort_values("country").reset_index(drop=True)[["country","product_name","price"]]

r

  country        product_name  price
0   Canda  Samsung Galaxy S20   1899
1   Canda           LG Velvet   1899
2   India    ASUS ROG Phone 5   1999
3   India    Oppo Find X3 Pro   1999
4      US           OnePlus 9   1999

In [26]:
import pandas as pd
p= pd.read_csv("products.csv")
s= pd.read_csv("suppliers.csv")

df= p.merge(s[["supplier_id","country"]], on ="supplier_id", how="left")

mp= df.groupby("country")["price"].agg(max_price="max")

r= df.merge(mp, on="country").query("price==max_price").sort_values("country").reset_index(drop=True)[["country","product_name","price"]]

r

  country        product_name  price
0   Canda  Samsung Galaxy S20   1899
1   Canda           LG Velvet   1899
2   India    ASUS ROG Phone 5   1999
3   India    Oppo Find X3 Pro   1999
4      US           OnePlus 9   1999